require(["appconfig"],function(){
    require([
        "spec/dataFlow_core",
        "spec/components/pointFromNumbers",
        "spec/sisl",
    ],function(){
        window.executeTests();
    });
});
